on:
  push:
    branches:
      - "main"
  pull_request:

name: "CI"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  ci:
    uses: "WebProject-xyz/.github/.github/workflows/ci.yml@72e0852530691b36a26a2d8df6e3edaa3ce779ed" # main
    secrets: inherit
    with:
      test-matrix: |
        [
          {"php-version": "8.3", "dependencies": "locked",  "with_coverage": true},
          {"php-version": "8.4", "dependencies": "highest", "with_coverage": false},
          {"php-version": "8.5", "dependencies": "highest", "with_coverage": false}
        ]
