on:
  push:
    branches:
      - "main"
  pull_request:

name: "CI"

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  ci:
    uses: "WebProject-xyz/.github/.github/workflows/ci.yml@7b5b8255bd5ef2d47a867195a05a5945fc2333f0" # main
    secrets: inherit
