on:
  push:
    branches:
      - "main"
  pull_request:

name: "CI"

permissions:
  contents: read

env:
  PHP_VERSION: "8.3"

jobs:
  configuration:
    name: "Configuration"
    runs-on: "ubuntu-latest"
    outputs:
      php-version: ${{ steps.determine-php-version.outputs.php-version }}
    steps:
      - name: "Determine PHP version"
        id: "determine-php-version"
        run: "echo \"php-version=${{ env.PHP_VERSION }}\" >> $GITHUB_OUTPUT"

  qa:
    name: "QA (lint + static analysis)"
    if: "!startsWith(github.event.head_commit.message, 'chore(release)')"
    runs-on: "ubuntu-latest"
    steps:
      -   name: "Checkout"
          uses: "actions/checkout@v4"

      -   name: "Install PHP"
          uses: "shivammathur/setup-php@v2"
          with:
            coverage: "none"
            php-version: "${{ env.PHP_VERSION }}"

      -   name: "Validate composer.json and composer.lock"
          run: "composer validate --ansi --strict"

      -   name: "Install dependencies with composer"
          run: "composer install --no-interaction --no-progress"

      -   name: "Build Codeception"
          run: "vendor/bin/codecept build"

      -   name: "Check coding style"
          run: "composer cs:check"

      -   name: "Run static analysis"
          run: "composer stan"

  tests:
    name: "Run codeception tests"
    needs: [ configuration, qa ]
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        include:
          - { php-version: "8.3", dependencies: locked, with_coverage: false }
          - { php-version: "8.4", dependencies: highest, with_coverage: false }
    steps:
      -   name: "Checkout"
          uses: "actions/checkout@v4"

      -   name: "Install PHP"
          uses: "shivammathur/setup-php@v2"
          with:
            coverage: "none"
            ini-values: display_errors=On, display_startup_errors=On, error_reporting=32767
            php-version: "${{ matrix.php-version }}"

      -   name: "Install dependencies with composer"
          run: "composer update --no-interaction --no-progress"

      -   name: "Run Tests"
          run: |
            vendor/bin/codecept build
            vendor/bin/codecept run --report
